python buildTableAndFindTemplates.py < enwiki.1.split.2.xml >> enwiki.id.title.template.csv
python buildTableAndFindTemplates.py < enwiki.2.split.2.xml >> enwiki.id.title.template.csv
python buildTableAndFindTemplates.py < enwiki.3.split.2.xml >> enwiki.id.title.template.csv
python buildTableAndFindTemplates.py < enwiki.4.split.2.xml >> enwiki.id.title.template.csv
python buildTableAndFindTemplates.py < enwiki.5.split.2.xml >> enwiki.id.title.template.csv
python buildTableAndFindTemplates.py < enwiki.6.split.2.xml >> enwiki.id.title.template.csv
python buildTableAndFindTemplates.py < enwiki.7.split.2.xml >> enwiki.id.title.template.csv
python buildTableAndFindTemplates.py < enwiki.8.split.2.xml >> enwiki.id.title.template.csv
python buildTableAndFindTemplates.py < enwiki.9.split.2.xml >> enwiki.id.title.template.csv
python buildTableAndFindTemplates.py < enwiki.10.split.2.xml >> enwiki.id.title.template.csv
python buildTableAndFindTemplates.py < enwiki.11.split.2.xml >> enwiki.id.title.template.csv
python buildTableAndFindTemplates.py < enwiki.12.split.2.xml >> enwiki.id.title.template.csv
python buildTableAndFindTemplates.py < enwiki.13.split.2.xml >> enwiki.id.title.template.csv
python buildTableAndFindTemplates.py < enwiki.14.split.2.xml >> enwiki.id.title.template.csv
python buildTableAndFindTemplates.py < enwiki.15.split.2.xml >> enwiki.id.title.template.csv
python buildTableAndFindTemplates.py < enwiki.16.split.2.xml >> enwiki.id.title.template.csv
python buildTableAndFindTemplates.py < enwiki.17.split.2.xml >> enwiki.id.title.template.csv
python buildTableAndFindTemplates.py < enwiki.18.split.2.xml >> enwiki.id.title.template.csv
python buildTableAndFindTemplates.py < enwiki.19.split.2.xml >> enwiki.id.title.template.csv
python buildTableAndFindTemplates.py < enwiki.20.split.2.xml >> enwiki.id.title.template.csv
python buildTableAndFindTemplates.py < enwiki.21.split.2.xml >> enwiki.id.title.template.csv
python buildTableAndFindTemplates.py < enwiki.22.split.2.xml >> enwiki.id.title.template.csv
python buildTableAndFindTemplates.py < enwiki.23.split.2.xml >> enwiki.id.title.template.csv
python buildTableAndFindTemplates.py < enwiki.24.split.2.xml >> enwiki.id.title.template.csv
python buildTableAndFindTemplates.py < enwiki.25.split.2.xml >> enwiki.id.title.template.csv
python buildTableAndFindTemplates.py < enwiki.26.split.2.xml >> enwiki.id.title.template.csv
python buildTableAndFindTemplates.py < enwiki.27.split.2.xml >> enwiki.id.title.template.csv
